CREATE TABLE balance_sheet
(
    symbol                               VARCHAR(5),
    start_date                           date,
    end_date                             date,
    cash_and_cash_equivalents_current    int,
    marketable_securities_current        int,
    accounts_receivable_current          int,
    inventories_current                  int,
    vendor_non_trade_receivables_current int,
    other_assets_current                 int,
    marketable_securities_non_current    int,
    property_plant_equipment_non_current int,
    other_assets_non_current             int,
    total_assets                         int,
    total_assets_current                 int,

    accounts_payable                     int,
    other_liabilities_current            int,
    deferred_revenue                     int,
    debt_current                         int,
    debt_non_current                     int,
    other_liabilities_non_current        int,
    total_liabilities                    int,
    total_liabilities_current            int,
    retained_earnings                    int,
    equity                               int,
    additional_paid_in_capital           int,
    PRIMARY KEY (symbol, start_date)
);

INSERT INTO balance_sheet(symbol,
                          start_date,
                          end_date,
                          cash_and_cash_equivalents_current,
                          marketable_securities_current,
                          accounts_receivable_current,
                          inventories_current,
                          vendor_non_trade_receivables_current,
                          other_assets_current,
                          marketable_securities_non_current,
                          property_plant_equipment_non_current,
                          other_assets_non_current,
                          total_assets,
                          total_assets_current,
                          accounts_payable,
                          other_liabilities_current,
                          deferred_revenue,
                          debt_current,
                          debt_non_current,
                          other_liabilities_non_current,
                          total_liabilities,
                          total_liabilities_current,
                          retained_earnings,
                          equity,
                          additional_paid_in_capital)
VALUES ('AAPL',
        '2019-09-29',
        '2020-09-26',
        34940,
        27699,
        26278,
        6580,
        25228,
        14111,
        127877,
        39440,
        48849,
        351002,
        134836,
        54763,
        47493,
        7612,
        15613,
        109106,
        53325,
        287912,
        125481,
        5562,
        63090,
        351002);